### PR TITLE
Add pinterest button and reorganize social sharing

### PR DESCRIPTION
**Pull request by msevestre**
First step in better social experience
I created one template for each social media (facebook, twitter, g+ and pinterest)
Also social media are only displayed when information is available

Finally, I corrected the facebook template which was using some unknown app_id...... that is user specific and needs to be set per user!

### CODE REVIEW

**Comment by jipiboily** [comment]
@msevestre I guess we can close this or is it still planned? It's been a year :)

Closing, feel free to re-open.

**Comment by msevestre** [comment]
Did you merged it? Problem was and still remains Travis

**Comment by jipiboily** [comment]
Nope, I did not.



(null)

**Comment by msevestre** [comment]
Hum why not? The only piece missing was the merge wasn't it?

**Comment by jipiboily** [comment]
I think it was not merging cleanly, re-opening.

**Comment by jipiboily** [comment]
@msevestre yeah, conflicts that needs to be resolved.

**Comment by msevestre** [comment]
ok will look at that. hard to dig into code after such a  long time

**Comment by msevestre** [comment]
done. Simple conflict in configuration.rb

**Pull request merged**
