### PR TITLE
modified migration files

### PR DESCRIPTION
**Pull request by omricohen**
I removed all the migration updates and moved them into 4 their respective create migrations. This will greatly simplify new installs.

### CODE REVIEW

**Comment by msevestre** [comment]
I fixed the build. Should be back in businesss soon

**Comment by msevestre** [comment]
@omricohen could you somehow update that PR to trigger the build again?Thanks

**Comment by omricohen** [comment]
@msevestre I did -- still failed

**Comment by msevestre** [comment]
yeah thanks. @jipiboily is going to look into that soon :)

**Comment by jipiboily** [comment]
yeah, I want to make the build pass again shortly. :)

**Comment by jipiboily** [comment]
@omricohen while working on making the build pass (#301) I had to resetup Monologue locally, and the migrations worked perfectly fine for me.

What is this PR trying to fix/change exactly? Not 100% clear to me.

Thanks!

**Comment by jipiboily** [comment]
That's going to be more complicated than I thought. See #301 please. Happy to pay $100 if someone wants to get Monologue back on track.

**Comment by jipiboily** [comment]
Actually, see https://github.com/jipiboily/monologue/issues/314 instead.

**Comment by omricohen** [comment]
@jipiboily This PR makes it so that you can rollback a monologue install. The current migrations do not allow for a rollback. Plus, not point in keeping so many migration 'change' files, makes it harder to maintain and understand what is going on.

**Comment by msevestre** [comment]
I am going to close this PR as it is polluting my Review list and is clearly outdated :)

**Pull request closed without merging**
