### PR TITLE
upgrade all the things (upgrade to Rails 5)

### PR DESCRIPTION
**Pull request by jipiboily**

### CODE REVIEW

**Comment by illegalnumbers** [comment]
Let's merge this! Some of my builds fail due to some of the older Ruby versions problems.

**Comment by jipiboily** [comment]
@illegalnumbers yeah, not that I don't want to but I was not able to figure it out when I looked briefly last week. Any idea maybe? I can look a bit later.

**Comment by illegalnumbers** [comment]
Honestly I really wasn't even able to get the test suite up and running locally since it's dependencies are so out of date...it might just be worth it to merge this guy in to get the builds to build the right Ruby versions and then just update the other libraries and fix tests on an as needed basis.

**Comment by msevestre** [comment]
Time to move on indeed :)

**Comment by jipiboily** [comment]
Going to work on this shortly.

**Comment by jipiboily** [comment]
ok, this isn't going to be trivial. We need a full upgrade, and it hasn't happened in a while.

There are a lot of deprecations, which we can live with for a few weeks/months until Rails 5.1 is out. That said, I can't get the tests running locally at all. I removed some gems, upgraded others, still not working.

Issues are with the Capybara tests (surprise! This is brittle!).

If someone wants to make Monologue Rails 5.0 compatible and ideally 5.1 ready, get in touch please. I can pay $100. It's not a lot, but it's open source and I don't even use it myself anymore 😀

**Comment by jipiboily** [comment]
Closing in favor of https://github.com/jipiboily/monologue/issues/314

**Pull request closed without merging**
